--- avidemux_plugins/cmake/admCheckFaad.cmake.orig	2025-01-10 17:40:16 UTC
+++ avidemux_plugins/cmake/admCheckFaad.cmake
@@ -15,15 +15,15 @@ MACRO(checkFaad)
 			FIND_HEADER_AND_LIB(FAAD faad.h faad)
 
 			IF(FAAD_FOUND)
-				ADM_CHECK_FUNCTION_EXISTS(faacDecInit "${FAAD_LIBRARY_DIR}" FAACDEC_FUNCTION_FOUND "" -I"${FAAD_INCLUDE_DIR}")
+#				ADM_CHECK_FUNCTION_EXISTS(faacDecInit "${FAAD_LIBRARY_DIR}" FAACDEC_FUNCTION_FOUND "" -I"${FAAD_INCLUDE_DIR}")
 
-				IF(NOT FAACDEC_FUNCTION_FOUND)
+#				IF(NOT FAACDEC_FUNCTION_FOUND)
 					ADM_CHECK_FUNCTION_EXISTS(NeAACDecInit "${FAAD_LIBRARY_DIR}" NEAACDEC_FUNCTION_FOUND "" -I"${FAAD_INCLUDE_DIR}")
 
 					IF(NOT NEAACDEC_FUNCTION_FOUND)
 						SET(FAAD_FOUND 0)
 					ENDIF()
-				ENDIF()
+#				ENDIF()
 			ENDIF()
 
 			PRINT_LIBRARY_INFO("FAAD" FAAD_FOUND "${FAAD_INCLUDE_DIR}" "${FAAD_LIBRARY_DIR}")
